### ISSUE TITLE
It Works but!

### ISSUE THREAD

**Issue by lanche11** [n7nix/rpi-temp-graph#1]
I have gotten this to work. But only after having to move the file "bin" that was created in /home/pi elsewhere. Then making the directory /home/pi/bin and copying all the files on the file list from rpi-temp-graph directory. Then running the install program. The crontab created had to be deleted and re-created to work otherwise it stalled the temp updates.

I would like to change to Celsius if you have any shortcut I would appreciate it.

**Comment by n7nix** [comment]
You are correct bin is not a file but a local directory. I realize that I assume you have done a core install of the DRAWS software which is not a requirement. I will look at what it takes to install it without that. Will also look at an option to change from F to C. Thanks for trying it out. Are you using a DHT11 to measure ambient temperature?

**Comment by lanche11** [comment]
No to the DRAW  
Yes to the DHT11. After installing the Adafruit DHT files it woke up. All values were U. It has been running for 2 days. This is a old NOOBS raspberrypi image on a rpi3b+. It would not work on the Buster image.

**Comment by n7nix** [comment]
I am testing changes that will fix your install bin problem and have a relatively easy method to change temperature from Fahrenheit to Celsius. I only verify with the current Raspberry Pi OS Buster image.

**Comment by n7nix** [comment]
Fixed with the following commits:
[Add note on updating scripts only](https://github.com/n7nix/rpi-temp-graph/commit/c92f9b8ac93c63e521501e468a4b8bfaa954ec6d)
[Add descriptions for scripts used in debugging DHT11 sensor](https://github.com/n7nix/rpi-temp-graph/commit/cd2d180bc6014ef391e9f1f7abda6e25c0aada7a)
[Replace static ifdef with DEBUG conditional to display humidity](https://github.com/n7nix/rpi-temp-graph/commit/7805e535ac3966d3c8acbad70682733b65c363fc)
[Add ability to more easily switch temperature units from Fahrenheit](https://github.com/n7nix/rpi-temp-graph/commit/1274077ab8e9633b2f019598b7daef980ed4f54a)
[Add ability to more easily switch temperature units from Fahrenheit](https://github.com/n7nix/rpi-temp-graph/commit/9b832674647c58ac7b3d56e13af4dc75caf74316)
[Fix check of file copy](https://github.com/n7nix/rpi-temp-graph/commit/f508477a6b9614111750483f6a5857381ea1acc4)
